spring:
  cloud:
    consul:
      discovery:
        register: false
    gateway:
      discovery:
        locator:
          enabled: true
  redis:
    host: 47.102.201.250
    port: 6379
    password: drango
    database: 0
email-verify-url: "http://139.159.132.32:8848/register.html?code="
logging:
  level:
    com.github.drango.microservices.gateway: debug
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 6000