spring:
  zipkin:
    base-url: http://zipkin-server/
  sleuth:
    sampler:
      probability: 1.0
sidecar:
  port: 8820
  health-uri: http://localhost:${sidecar.port}/health
eureka:
  client:
    enabled: false
logging:
  level:
    root: info
    com.github.drango.microservices.mail: debug
  path: ./logs/${server.port}
  file:
    max-size: 1000MB
#zuul:
#  host:
#    connect-timeout-millis: 5000
