spring:
  jackson:
    default-property-inclusion: non_empty
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    consul:
      host: 127.0.0.1
      port: 8500
      config:
        watch:
          enabled: true
      discovery:
#        serviceName: gateway
#        healthCheckInterval: 10s
        register: false
#  session:
#    store-type: redis
#    redis:
#      flush-mode: on_save
#      namespace: microservices:gateway:session
#    timeout: 100
  redis:
    host: 47.102.201.250
    port: 6379
    password: drango
    database: 0
  zipkin:
    base-url: http://zipkin-server/
  sleuth:
   sampler:
    probability: 1.0
logging:
  level:
    root: info
    com.github.drango.microservices.gateway: debug
  path: ./logs/8800
  file:
    max-size: 1000MB
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 6000