spring:
  jackson:
    default-property-inclusion: non_empty
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    consul:
      host: 127.0.0.1
      port: 8500
      config:
        watch:
          enabled: true
      discovery:
#        serviceName: gateway
#        healthCheckInterval: 10s
        register: false
logging:
  level:
    root: debug
#    org:
#      springframework:
#        cloud:
#          gateway: debug
#    com.jiuwei.minapp: debug
  path: ./logs/8800
  file:
    max-size: 1000MB
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 6000