spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      config:
        watch:
          enabled: true
      discovery:
        serviceName: zipkin-server
        healthCheckInterval: 10s